apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-admin
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command: ['cat']
      tty: true
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ['cat']
      tty: true