apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-admin
  containers:
    - name: snyk
      image: snyk/snyk:latest
      imagePullPolicy: IfNotPresent
      command: ['cat']
      tty: true
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.5.1-debug
      imagePullPolicy: IfNotPresent
      command:
      - /busybox/cat
      tty: true
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /kaniko/.docker
    - name: kubectl
      image: gcr.io/cloud-builders/kubectl
      imagePullPolicy: IfNotPresent
      command: ['cat']
      tty: true
  volumes:
    - name: jenkins-docker-cfg
      projected:
        sources:
        - secret:
            name: docker-credentials
            items:
              - key: .dockerconfigjson
                path: config.json