apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-admin
  containers:
    # - name: gcloud
    #   image: gcr.io/cloud-builders/gcloud
    #   command: ['cat']
    #   tty: true
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ['cat']
      tty: true